[package]
name = "HAL9000-Chat-Bot"
version = "0.1.0"
authors = ["Robin und Sebastian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
