[package]
name = "HAL9000-Chat-Bot"
version = "0.1.0"
authors = ["Robin und Sebastian"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="hal_9000"
path="src/main.rs"


[dependencies]
log = "0.4.8"
simple_logger = "1.6.0"