version: "3.7"
services:
  rust_bot:
    build:
      dockerfile: .docker/bot.Dockerfile
      context: .
    container_name: rust_bot
    restart: always
    volumes:
      - ./src:/usr/app/src
      - ./Cargo.toml:/usr/app/Cargo.toml
      - ./Cargo.lock:/usr/app/Cargo.lock
    env_file:
      - .env
    depends_on:
      - database
    entrypoint: ["cargo", "watch", "-x", "run"]
    links:
      - "database:mongo"

  database:
    image: mongo:4.2
    container_name: database
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db

volumes:
  mongodb_data: