name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1.0
      with:
    # The filename for the envfile
        file_name: .env
    - name: Docker
      run: docker-compose up -d
    #- name: Run tests
     # run: cargo test
